//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Applications
    {
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public int CandidateID { get; set; }
        public int PositionID { get; set; }
        public int GradeID { get; set; }
        public Nullable<int> ManagerID { get; set; }
        public Nullable<int> RecruiterID { get; set; }
        public bool IsSent { get; set; }
    
        public virtual Candidates Candidates { get; set; }
        public virtual Grades Grades { get; set; }
        public virtual Managers Managers { get; set; }
        public virtual Positions Positions { get; set; }
        public virtual Recruiters Recruiters { get; set; }
    }
}
