//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application_Recruiter
    {
        public int ID { get; set; }
        public int ApplicationID { get; set; }
        public int RecruiterID { get; set; }
    
        public virtual Applications Applications { get; set; }
        public virtual Recruiters Recruiters { get; set; }
    }
}
